### ISSUE TITLE
Package error in julia_by_example

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#109]
![image](https://user-images.githubusercontent.com/13106721/132161293-1d1dcd97-dca5-4bb9-8b99-b7e0a9d7421e.png)

@jbrightuniverse I was seeing an issue in this section of the julia_by_example.  Lets see if it is on the latest versions, and if so then we will want to see what changed.

**Comment by jbrightuniverse** [comment]
That's odd because if I go to the current build [here](https://quantecon.github.io/lecture-julia.myst/getting_started_julia/julia_by_example.html#using-a-package), the warning doesn't show up.

**Comment by jlperla** [comment]
Not sure, but the build could be having caching problems. Would try on your desktop

**Comment by jbrightuniverse** [comment]
Running a fresh, local build yields this warning. The warning disappears if I then `] up StaticArrays`, which does the following package changes:

![image](https://user-images.githubusercontent.com/30967260/132265219-607be084-5475-459e-9343-f8c5fa964beb.png)

The issue seems to be versioning incompatibility with the particular instance of `ArrayInterface`.

**Comment by jlperla** [comment]
Perfect. I would do that `up`

**Comment by jlperla** [comment]
If you can tell @mmcky when we are good to go, then hopefully we have all changes complete for the release.

**Comment by mmcky** [comment]
thanks @jbrightuniverse -- the latest `cache` build is running now so that error should show up. Let me know when fixed.

**Comment by mmcky** [comment]
This looks fixed in the latest `publish` build

https://quantecon.github.io/lecture-julia.myst/getting_started_julia/julia_by_example.html#using-a-package
