### ISSUE TITLE
LaTeXStrings.jl demo in section 8.5.1 doesn't escape latex properly

### ISSUE THREAD

**Issue by jbrightuniverse** [QuantEcon/lecture-julia.myst#40]
```
using LaTeXStrings
L"an equation: $1 + \alpha^2$"
```

The code in [8.5.1](https://github.com/QuantEcon/lecture-julia.myst/blob/main/lectures/more_julia/general_packages.md#latexstringsjl) renders latex with inverted formatting; the "an equation" part is rendered as math, and 1+\alpha^2 as text.
![image](https://user-images.githubusercontent.com/30967260/129612953-57a20b22-68c7-4eb9-9183-4555565839e8.png)

**Comment by jlperla** [comment]
When you post issues like this, try to see if it is working properly in the generated notebooks.  If not, then it says it is a package/julia problem rather than a jupyterbook one.

In this case, my guess is that the latexstrings.jl changed and that approach is no longer correct.  You could try changing it to

```
using LaTeXStrings
L"1 + \alpha^2"
```
instead and see how it does.

**Comment by jbrightuniverse** [comment]
In the generated notebook, it looks fine. Rebuilding the HTML, the issue remains in the HTML page, so this would seem to be a different problem.

**Comment by jlperla** [comment]
I am removing this example.  This isn't worth the trouble here.
