### ISSUE TITLE
Evaluate removing Dierkx dependency to DataInterpolations

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#49]
Currently it is only used in the amss lecture.  Search for `Spline1D` in vscode.  The reason it was used was that Interpolations.jl doesn't support splines on irregular data.

- [x] Add a DataInterpolations to the package dependencies (and remove Dierkx eventually)
- [x] In the AMSS lecture, get rid of the `using Dierckx` and convert over the `Spline1D(x, y)` calls to `CubicSpline(y, x)` and use DataInterpolations instead.
    - But crucially!  Note that the order of the arguments is different in datainterpolations
- [x] Carefully check the results to make sure they are the same.  There may not be sufficient unit testing in that lecture.
- [x] Convert over the linear interpolation used in the lecture as well to use the DataInterpolations (as I think it was using Dierkx for both).
- [ ] Change the link to `general_packages.md` to a link to datainterpolations instead.

**Comment by jbrightuniverse** [comment]
Two things noticed:

First, everything seems more or less the same, the only thing noticeably different is this original chart set:
![image](https://user-images.githubusercontent.com/30967260/130128892-189cbaa6-0e7f-4e57-aab9-b05000590d91.png)
has some slightly different spacing:
![image](https://user-images.githubusercontent.com/30967260/130128947-9c48a4f5-2fdf-41a1-a933-6b8e7b370907.png)

Second, directly doing `using DataInterpolations` doesn't work. Specifically, no matter where I put it, it causes the `optimize()` function used by another library to suddenly become not defined. I'm not sure why this is. If I instead do `import DataInterpolations.CubicSpline`, the error disappears since the package is now not being fully imported. But I'm not sure if this is what we want to do.
