### ISSUE TITLE
Odd output in the build log for a tools_and_techniques lecture?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#96]
The output of jupyterbook says
```
writing additional pages... search done
copying images... [100%] C:/Users/jesse/Documents/GitHub/lecture-julia.myst/lectures/_build/jupyter_execute/tools_and_techniques/stationary_densities_22_0.png.pngpng
copying static files... done
```

Which may or may not be a problem?  but the file extension is odd.  @jbrightuniverse  Can you take a look at this (on the `testing` branch perhaps, where I saw it) to make sure that the figures themselves display correctly in that lecture?

**Comment by jlperla** [comment]
@jbrightuniverse  I am going to create a separate issue for this and revert any package changes in my particular `testing` branch.  Bad discipline on my part.

**Comment by jbrightuniverse** [comment]
I suspect this is not a problem because a. it shows up fine in the HTML and b. it shows up fine in the folder structure with the correct extensions. In the terminal, this line is overwritten for every image being processed so it might be the case that these are residual extensions from previous lines. Regardless of the issue, it does not impact the output.

**Comment by jlperla** [comment]
Sounds good, will close
